# Generated by Django 5.0.2 on 2024-05-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_diagnosis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescribedmedication',
            unique_together=set(),
        ),
    ]
