# Generated by Django 5.0.2 on 2024-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_checkup_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
