# Generated by Django 5.0.2 on 2024-12-05 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_checkup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedication',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
